[settings]
# DNS Configuration
use_local_dns = 0
use_external_dns = 1
dns_servers = 8.8.8.8, 1.1.1.1, 208.67.222.222, 9.9.9.9

# Domain files to process
domains_files = domains.txt

# Monitoring settings
monitoring_duration_minutes = 5
monitoring_interval_seconds = 30

# Network settings
subnet_mask = 24

# Output files (now in result directory) you can change it after =
output_domain_ip = result/domain_ip_settings.txt
output_only_ipv4 = result/only_ipv4_settings.txt
output_keenetic = result/keenetic_settings.bin

# Log file
log_file = result/script_run.log